### ISSUE TITLE
k8s的yaml配置的一些细节

### ISSUE THREAD

**Issue by wtysos11** [wtysos11/blogWiki#220]
[多行字符串配置方法](https://juejin.cn/post/6844903972688363534)

变量设置：比如在statefulset中可以使用$(NAME)作为之后pod的名称，从而进行label的设置
```yaml
        - args:
            - rule
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --rule-file=/etc/thanos/rules/*rules.yaml
            - --objstore.config-file=/etc/thanos/objectstorage.yaml
            - --data-dir=/var/thanos/rule
            - --label=rule_replica="$(NAME)" #这个地方进行了全局变量的使用，从而完成label的设置
            - --alert.label-drop="rule_replica"
            - --query=dnssrv+_http._tcp.thanos-query.monitoring.svc.cluster.local
            - --alertmanagers.url=http://alertmanager-main.monitoring.svc.cluster.local:9093
          env:
            - name: NAME #这个地方设置了全局变量
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
```
这方面的详情可以查看[inject-data-application](https://kubernetes.io/docs/tasks/inject-data-application/_print/)

dnssrv参数
在yaml文件中有类似的片段`--query=dnssrv+_http._tcp.thanos-query.monitoring.svc.cluster.local`，其中dnssrv居然是可以被访问的，非常厉害。
